# Generated by Django 6.0.5 on 2026-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_before_after', models.BooleanField(default=False)),
                ('image_before', models.ImageField(blank=True, null=True, upload_to='projects/before/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Prakash Devkota', max_length=100)),
                ('title', models.CharField(default='Thumbnail Designer', max_length=100)),
                ('hero_kicker', models.CharField(default='Premium Thumbnail Design', max_length=100)),
                ('hero_title_line1', models.CharField(default='Make Them', max_length=100)),
                ('hero_title_span', models.CharField(default='Stop Scrolling.', max_length=100)),
                ('hero_description', models.TextField(default='I create high-impact YouTube thumbnails with strong hooks, bold composition, and a premium visual system built for serious creators.')),
                ('about_title', models.CharField(default='Turn Scrollers Into Viewers.', max_length=200)),
                ('about_text', models.TextField(default='I design high-converting YouTube thumbnails that capture attention, spark curiosity, and drive clicks. Let’s stop losing your audience to the feed and start.')),
                ('solve_title', models.CharField(default='What I Can Solve For You', max_length=200)),
                ('solve_text_1', models.TextField(default="I am a professional thumbnail strategist with over a year of experience. I specialize in boosting your channel's CTR and views by creating high-impact visuals that grab attention instantly.")),
                ('solve_text_2', models.TextField(default='My designs ensure maximum mobile readability and clarity, helping you deliver the high performance and professional look your channel deserves.')),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('discord_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('channel_link', models.URLField(blank=True)),
                ('review_text', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('sub_count', models.CharField(blank=True, help_text='e.g. 1.69M Subscribers', max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
